In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [19]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [20]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [21]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [22]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [23]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [24]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [25]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [28]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [29]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\prakh\Desktop\ANNClassification\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [30]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  
])

model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From c:\Users\prakh\Desktop\ANNClassification\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\prakh\Desktop\ANNClassification\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [31]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [32]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [33]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\prakh\Desktop\ANNClassification\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\prakh\Desktop\ANNClassification\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 3ms/step - loss: 100376.8438 - mae: 100376.8438 - val_loss: 98521.3828 - val_mae: 98521.3828
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 99653.9219 - mae: 99653.9219 - val_loss: 97070.6641 - val_mae: 97070.6641
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 97105.3125 - mae: 97105.3125 - val_loss: 93341.6250 - val_mae: 93341.6250
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 92065.9219 - mae: 92065.9219 - val_loss: 87072.1172 - val_mae: 87072.1172
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 84674.8984 - mae: 84674.8984 - val_loss: 78921.9844 - val_mae: 78921.9844
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 75858.3906 - mae: 75858.3906 - val_loss: 70203.7344 - val_mae: 70203.7344
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 67193.7812 - mae: 67193.7812 - val_loss: 62439.4336 - val_mae: 62439.4336
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 59992.8164 - mae: 59992.8164 - val_loss: 56589.1680 - val_mae: 56589.1680
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 55103.5117 - mae: 55103.5117 - val_loss: 53144.2891 - val_mae: 53144.2891
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 52365.0195 - mae: 52365.0195 - val_loss: 51441.5273 - val_mae: 51441.5273
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 51061.5898 - mae: 51061.5898 - val_loss: 50895.6602 - val_mae: 50895.6602
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50557.5391 - mae: 50557.5391 - val_loss: 50743.9609 - val_mae: 50743.9609
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50317.6289 - mae: 50317.6289 - val_loss: 50696.2812 - val_mae: 50696.2812
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 50209.3789 - mae: 50209.3789 - val_loss: 50659.6523 - val_mae: 50659.6523
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 50140.7734 - mae: 50140.7734 - val_loss: 50628.4258 - val_mae: 50628.4258
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 50089.4258 - mae: 50089.4258 - val_loss: 50592.6328 - val_mae: 50592.6328
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 50045.9766 - mae: 50045.9766 - val_loss: 50562.4414 - val_mae: 50562.4414
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50007.9688 - mae: 50007.9688 - val_loss: 50540.8047 - val_mae: 50540.8047
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 49972.0977 - mae: 49972.0977 - val_loss: 50518.3086 - val_mae: 50518.3086
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49942.7422 - mae: 49942.7422 - val_loss: 50496.9023 - val_mae: 50496.9023
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49917.5039 - mae: 49917.5039 - val_loss: 50482.0234 - val_mae: 50482.0234
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49889.3828 - mae: 49889.3828 - val_loss: 50459.0625 - val_mae: 50459.0625
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 49866.5430 - mae: 49866.5430 - val_loss: 50446.0742 - val_mae: 50446.0742
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49842.7695 - mae: 49842.7695 - val_loss: 50432.4219 - val_mae: 50432.4219
Epoch 25/100
250/250 [==============================] - 1s 2ms/step - loss: 49826.0273 - mae: 49826.0273 - val_loss: 50419.3594 - val_mae: 50419.3594
Epoch 26/100
250/250 [==============================] - 1s 2ms/step - loss: 49808.8477 - mae: 49808.8477 - val_loss: 50400.3008 - val_mae: 50400.3008
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49783.2227 - mae: 49783.2227 - val_loss: 50386.1562 - val_mae: 50386.1562
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49767.5195 - mae: 49767.5195 - val_loss: 50374.5508 - val_mae: 50374.5508
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49749.0469 - mae: 49749.0469 - val_loss: 50374.0195 - val_mae: 50374.0195
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 49733.4844 - mae: 49733.4844 - val_loss: 50365.9336 - val_mae: 50365.9336
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 49717.4766 - mae: 49717.4766 - val_loss: 50357.7539 - val_mae: 50357.7539
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 49704.3242 - mae: 49704.3242 - val_loss: 50352.9297 - val_mae: 50352.9297
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49694.4844 - mae: 49694.4844 - val_loss: 50353.4453 - val_mae: 50353.4453
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49674.8555 - mae: 49674.8555 - val_loss: 50352.3711 - val_mae: 50352.3711
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49663.3828 - mae: 49663.3828 - val_loss: 50349.8359 - val_mae: 50349.8359
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 49649.6680 - mae: 49649.6680 - val_loss: 50341.7812 - val_mae: 50341.7812
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 49639.1914 - mae: 49639.1914 - val_loss: 50335.8086 - val_mae: 50335.8086
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49628.5625 - mae: 49628.5625 - val_loss: 50334.1367 - val_mae: 50334.1367
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 49617.2617 - mae: 49617.2617 - val_loss: 50333.5352 - val_mae: 50333.5352
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 49605.1055 - mae: 49605.1055 - val_loss: 50327.9844 - val_mae: 50327.9844
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 49594.8516 - mae: 49594.8516 - val_loss: 50323.2891 - val_mae: 50323.2891
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 49585.5117 - mae: 49585.5117 - val_loss: 50323.5430 - val_mae: 50323.5430
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49574.4219 - mae: 49574.4219 - val_loss: 50324.6914 - val_mae: 50324.6914
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49567.1055 - mae: 49567.1055 - val_loss: 50324.2305 - val_mae: 50324.2305
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49554.9141 - mae: 49554.9141 - val_loss: 50322.8398 - val_mae: 50322.8398
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 49546.1250 - mae: 49546.1250 - val_loss: 50315.8477 - val_mae: 50315.8477
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 49538.3047 - mae: 49538.3047 - val_loss: 50316.3398 - val_mae: 50316.3398
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49530.4336 - mae: 49530.4336 - val_loss: 50320.6289 - val_mae: 50320.6289
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 49522.7656 - mae: 49522.7656 - val_loss: 50323.4961 - val_mae: 50323.4961
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 49514.4609 - mae: 49514.4609 - val_loss: 50319.4023 - val_mae: 50319.4023
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49506.1992 - mae: 49506.1992 - val_loss: 50316.6719 - val_mae: 50316.6719
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49502.9375 - mae: 49502.9375 - val_loss: 50308.2227 - val_mae: 50308.2227
Epoch 53/100
250/250 [==============================] - 1s 2ms/step - loss: 49495.5078 - mae: 49495.5078 - val_loss: 50307.4648 - val_mae: 50307.4648
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49488.3633 - mae: 49488.3633 - val_loss: 50300.7734 - val_mae: 50300.7734
Epoch 55/100
250/250 [==============================] - 1s 2ms/step - loss: 49483.2852 - mae: 49483.2852 - val_loss: 50312.5547 - val_mae: 50312.5547
Epoch 56/100
250/250 [==============================] - 1s 2ms/step - loss: 49476.0781 - mae: 49476.0781 - val_loss: 50324.2109 - val_mae: 50324.2109
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 49467.2773 - mae: 49467.2773 - val_loss: 50306.6445 - val_mae: 50306.6445
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 49462.3008 - mae: 49462.3008 - val_loss: 50312.0312 - val_mae: 50312.0312
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 49457.2812 - mae: 49457.2812 - val_loss: 50313.3945 - val_mae: 50313.3945
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 49450.1953 - mae: 49450.1953 - val_loss: 50317.8594 - val_mae: 50317.8594
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49446.1680 - mae: 49446.1680 - val_loss: 50318.1758 - val_mae: 50318.1758
Epoch 62/100
250/250 [==============================] - 1s 2ms/step - loss: 49439.2422 - mae: 49439.2422 - val_loss: 50317.3750 - val_mae: 50317.3750
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 49435.7422 - mae: 49435.7422 - val_loss: 50326.7656 - val_mae: 50326.7656
Epoch 64/100
250/250 [==============================] - 1s 2ms/step - loss: 49429.9336 - mae: 49429.9336 - val_loss: 50321.2227 - val_mae: 50321.2227

In [34]:
%load_ext tensorboard

In [35]:
%tensorboard --logdir regressionlogs/fit

In [36]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 2ms/step - loss: 50300.7734 - mae: 50300.7734
Test MAE : 50300.7734375

In [37]:
model.save('regression_model.h5')

c:\Users\prakh\Desktop\ANNClassification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(